export default [
  {
    id: 'TM.PR.20211020.03',
    name: 'Tomato',
    subcategory: 'Pear Tomato',
    type: 'Wet',
    weight: '9',
    finalProduct: 'Dried Tomatoes',
    startTime: '11:00',
    duration: 3,
    location: 'A1',
    vendorId: 'ABC101',
    vendorName: 'Main Market',
    imageUrl:
      'https://image.freepik.com/free-photo/top-view-ripe-fresh-tomatoes-with-water-drops-black-background_141793-3432.jpg',
    imageName: 'image.jpg',
    variety: 'Large',
    dayOfDrying: '2021-10-20',
    staffId: 'MH101',
    polyhouse: '1',
  },
  {
    id: 'TM.PR.20211020.04',
    name: 'Tomato',
    subcategory: 'Pear Tomato',
    type: 'Wet',
    weight: '9',
    finalProduct: 'Dried Tomatoes',
    startTime: '11:00',
    duration: 3,
    location: 'B1',
    vendorId: 'ABC101',
    vendorName: 'Main Market',
    imageUrl:
      'https://image.freepik.com/free-photo/top-view-ripe-fresh-tomatoes-with-water-drops-black-background_141793-3432.jpg',
    imageName: 'image.jpg',
    variety: 'Large',
    dayOfDrying: '2021-10-20',
    staffId: 'MH101',
    polyhouse: '1',
  },
  {
    id: 'TM.GR.20211021.05',
    name: 'Tomato',
    variety: 'Green Tomato',
    type: 'Wet',
    weight: 15,
    finalProduct: 'Dried Tomatoes',
    startTime: '09:00',
    duration: 4,
    location: 'C1',
    vendorId: 'VICTOR04',
    vendorName: 'Victor Agencies',
    imageUrl:
      'https://image.freepik.com/free-photo/top-view-ripe-fresh-tomatoes-with-water-drops-black-background_141793-3432.jpg',
    imageName: 'image.jpg',
    dayOfDrying: '2021-10-21',
    staffId: 'RS301',
    polyhouse: '2',
  },
]
